AWSTemplateFormatVersion: '2010-09-09'
Description: aws-glue-dynamodb-export-csv-datastore
Parameters:
  ProjectName:
    Type: String
    Description: Project Name
  StageName:
    Type: String
    AllowedValues:
      - prod
      - stage
      - dev
    Description: Stage Name
Resources:
  ArticleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${ProjectName}-${StageName}-target
      AttributeDefinitions:
        - AttributeName: create_date
          AttributeType: S
        - AttributeName: sample_id
          AttributeType: N
      KeySchema:
        - AttributeName: create_date
          KeyType: HASH
        - AttributeName: sample_id
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: ${ProjectName}-${StageName}-result
